name: Deploy no AKS

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "k8s/**"
      - "Dockerfile"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Autenticar no Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login no Azure Container Registry (ACR)
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login acrprdbr001.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Configurar AKS e Kubectl
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name aks-spring-prd-br

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir aplicação com Maven
        run: mvn clean package -DskipTests

      - name: Construir e Enviar Docker para ACR
        run: |
          IMAGE_NAME="acrprdbr001.azurecr.io/congregacao-java:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Atualizar imagem no AKS
        run: |
          kubectl set image deployment/congregacao-java congregacao-java=acrprdbr001.azurecr.io/congregacao-java:latest --namespace default

      - name: Aplicar Configuração no AKS
        run: |
          kubectl apply -f k8s/secrets.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
