name: Deploy no AKS

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "k8s/**"
      - "Dockerfile"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Autenticar no Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Configurar AKS e Kubectl
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name aks-spring-prd-br

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir aplicação com Maven
        run: mvn clean package -DskipTests

      - name: Construir e Enviar Docker para GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/aqs-digital-services/congregacao-java:latest .
          docker push ghcr.io/aqs-digital-services/congregacao-java:latest

      - name: Aplicar Configuração no AKS
        run: |
          kubectl apply -f k8s/secrets.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml